[package]
name = "swizzle3d"
version = "0.1.0"
edition = "2021"

[dependencies]

minifb = "0.25"
glam = "0.27"
rayon = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
smallvec = "1"
